/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    events: Event;
    projects: Project;
    organizations: Organization;
    'board-members': BoardMember;
    media: Media;
    'contact-submissions': ContactSubmission;
    'grant-requests': GrantRequest;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    organizations: OrganizationsSelect<false> | OrganizationsSelect<true>;
    'board-members': BoardMembersSelect<false> | BoardMembersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'grant-requests': GrantRequestsSelect<false> | GrantRequestsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Create a page, then add and reorder the designed sections that make it up. Drag sections to change their order.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Used in the admin list, browser tab, and navigation unless you set a nav label.
   */
  title: string;
  /**
   * URL path. Use home for the homepage at /. Other pages become /your-slug, such as board-members.
   */
  slug: string;
  /**
   * Add a section, then drag it to the place it should appear on the public page.
   */
  layout?:
    | (
        | HeroBlock
        | MissionBlock
        | ImpactBlock
        | OrganizationsBlock
        | FeaturedProjectsBlock
        | PhotoRailBlock
        | UpcomingEventsBlock
        | DonateCtaBlock
        | ContactBlock
        | MastheadBlock
        | BoardListBlock
        | EventListBlock
        | ProjectLedgerBlock
        | GrantRequestBlock
      )[]
    | null;
  /**
   * Show this page in the header and footer.
   */
  showInNav?: boolean | null;
  /**
   * Optional shorter label for the navigation. Defaults to the page title.
   */
  navLabel?: string | null;
  /**
   * Lower numbers appear first. Home is usually 0.
   */
  navOrder?: number | null;
  /**
   * Browser tab and search title. Home is used as-is. Other pages append the site name automatically. Defaults to the page title.
   */
  metaTitle?: string | null;
  /**
   * Unique search listing description. Keep it concrete and specific to this page.
   */
  metaDescription?: string | null;
  /**
   * Optional social share image for this page. Falls back to the default share image in Site settings.
   */
  ogImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock".
 */
export interface HeroBlock {
  /**
   * Keep it short enough to stay on the first screen with Donate.
   */
  heading: string;
  /**
   * Add 1 photograph, or 3 for an offset cluster. Two also works.
   */
  photos?:
    | {
        image: number | Media;
        /**
         * CSS object-position, such as center or 30% 40%, so faces stay in crop.
         */
        position?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Used only when Photographs is empty.
   */
  fallbackImage?: (number | null) | Media;
  fallbackImagePosition?: string | null;
  /**
   * Optional second button beside Donate. Leave blank to hide it.
   */
  secondaryLabel?: string | null;
  secondaryHref?: string | null;
  /**
   * Fill behind this section. Teal, green, flare, and navy switch the type to light ink so it stays readable.
   */
  background?: ('paper' | 'tint' | 'teal' | 'field' | 'flare' | 'navy') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
/**
 * Photographs and files for the public site. Grant PDFs are stored as internal files and are never shown publicly. Production stores files in Vercel Blob.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Required for meaningful photographs. Describe the activity, people, and place. Leave blank only for PDFs or images marked decorative.
   */
  alt?: string | null;
  /**
   * Use for logos or purely decorative crops. The public site will use empty alt text so screen readers skip the image.
   */
  decorative?: boolean | null;
  /**
   * Internal files, including grant PDFs, are never returned to the public website.
   */
  visibility: 'public' | 'internal';
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    feature?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MissionBlock".
 */
export interface MissionBlock {
  /**
   * The large statement on the teal field.
   */
  heading: string;
  /**
   * Optional phrase in the heading to underline. It must match the heading exactly.
   */
  highlight?: string | null;
  body: string;
  /**
   * Optional quieter closing line.
   */
  note?: string | null;
  /**
   * Fill behind this section. Teal, green, flare, and navy switch the type to light ink so it stays readable.
   */
  background?: ('paper' | 'tint' | 'teal' | 'field' | 'flare' | 'navy') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mission';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImpactBlock".
 */
export interface ImpactBlock {
  heading?: string | null;
  intro?: string | null;
  /**
   * Up to three impact stories. Leave empty rather than inventing results.
   */
  stories?:
    | {
        heading: string;
        body: string;
        /**
         * Optional inscribed proof, such as a year, amount, or recipient.
         */
        proofLabel?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Fill behind this section. Teal, green, flare, and navy switch the type to light ink so it stays readable.
   */
  background?: ('paper' | 'tint' | 'teal' | 'field' | 'flare' | 'navy') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'impact';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OrganizationsBlock".
 */
export interface OrganizationsBlock {
  heading?: string | null;
  /**
   * Programs and facilities to show in this section.
   */
  organizations?: (number | Organization)[] | null;
  /**
   * Fill behind this section. Teal, green, flare, and navy switch the type to light ink so it stays readable.
   */
  background?: ('paper' | 'tint' | 'teal' | 'field' | 'flare' | 'navy') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'organizations';
}
/**
 * Recreation programs, facilities, and partners that Friends of Recreation supports. Do not invent partners.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations".
 */
export interface Organization {
  id: number;
  name: string;
  /**
   * Optional public website.
   */
  website?: string | null;
  /**
   * Optional logo. Keep organization logos secondary to photography on the public site.
   */
  logo?: (number | null) | Media;
  /**
   * One or two sentences about this program or facility.
   */
  summary?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedProjectsBlock".
 */
export interface FeaturedProjectsBlock {
  heading?: string | null;
  intro?: string | null;
  emptyMessage?: string | null;
  allLabel?: string | null;
  allHref?: string | null;
  /**
   * Fill behind this section. Teal, green, flare, and navy switch the type to light ink so it stays readable.
   */
  background?: ('paper' | 'tint' | 'teal' | 'field' | 'flare' | 'navy') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'featuredProjects';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PhotoRailBlock".
 */
export interface PhotoRailBlock {
  /**
   * Screen-reader heading for the photograph slider.
   */
  heading?: string | null;
  /**
   * Recreation photographs only. Organization logos belong on Organization records.
   */
  slides?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Fill behind this section. Teal, green, flare, and navy switch the type to light ink so it stays readable.
   */
  background?: ('paper' | 'tint' | 'teal' | 'field' | 'flare' | 'navy') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'photoRail';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "UpcomingEventsBlock".
 */
export interface UpcomingEventsBlock {
  heading?: string | null;
  /**
   * How many upcoming events to show. The first is featured.
   */
  limit?: number | null;
  emptyHeading?: string | null;
  emptyMessage?: string | null;
  allLabel?: string | null;
  allHref?: string | null;
  /**
   * Fill behind this section. Teal, green, flare, and navy switch the type to light ink so it stays readable.
   */
  background?: ('paper' | 'tint' | 'teal' | 'field' | 'flare' | 'navy') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'upcomingEvents';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DonateCtaBlock".
 */
export interface DonateCtaBlock {
  heading?: string | null;
  body?: string | null;
  /**
   * Optional second button beside Donate.
   */
  secondaryLabel?: string | null;
  secondaryHref?: string | null;
  /**
   * Fill behind this section. Teal, green, flare, and navy switch the type to light ink so it stays readable.
   */
  background?: ('paper' | 'tint' | 'teal' | 'field' | 'flare' | 'navy') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'donateCta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactBlock".
 */
export interface ContactBlock {
  statement?: string | null;
  heading?: string | null;
  intro?: string | null;
  /**
   * Optional photograph under the statement, beside the form. Leave blank to use a recent public photo.
   */
  photo?: (number | null) | Media;
  /**
   * CSS object-position, such as center or 30% 40%, so faces stay in crop.
   */
  photoPosition?: string | null;
  /**
   * Fill behind this section. Teal, green, flare, and navy switch the type to light ink so it stays readable.
   */
  background?: ('paper' | 'tint' | 'teal' | 'field' | 'flare' | 'navy') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contact';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MastheadBlock".
 */
export interface MastheadBlock {
  heading: string;
  lede?: string | null;
  /**
   * Optional supporting photograph. Leave blank to use a recent public photo.
   */
  photo?: (number | null) | Media;
  /**
   * Which recent public photograph to use when no photo is chosen. 0 is the newest.
   */
  photoFallbackIndex?: number | null;
  /**
   * Fill behind this section. Teal, green, flare, and navy switch the type to light ink so it stays readable.
   */
  background?: ('paper' | 'tint' | 'teal' | 'field' | 'flare' | 'navy') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'masthead';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BoardListBlock".
 */
export interface BoardListBlock {
  heading?: string | null;
  emptyHeading?: string | null;
  emptyMessage?: string | null;
  emptyNote?: string | null;
  /**
   * Fill behind this section. Teal, green, flare, and navy switch the type to light ink so it stays readable.
   */
  background?: ('paper' | 'tint' | 'teal' | 'field' | 'flare' | 'navy') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'boardList';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EventListBlock".
 */
export interface EventListBlock {
  upcomingHeading?: string | null;
  pastHeading?: string | null;
  emptyHeading?: string | null;
  emptyMessage: string;
  /**
   * Fill behind this section. Teal, green, flare, and navy switch the type to light ink so it stays readable.
   */
  background?: ('paper' | 'tint' | 'teal' | 'field' | 'flare' | 'navy') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'eventList';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProjectLedgerBlock".
 */
export interface ProjectLedgerBlock {
  /**
   * Heading above the five project categories.
   */
  categoryHeading?: string | null;
  /**
   * Optional sentence under the category heading. Leave blank to let the five names speak.
   */
  categoryIntro?: string | null;
  /**
   * Leave blank to use the funded-year range from published projects.
   */
  heading?: string | null;
  /**
   * Shown beside the ledger heading. Use this to say the history is pending board confirmation.
   */
  confirmationNote?: string | null;
  emptyHeading?: string | null;
  emptyMessage?: string | null;
  /**
   * Fill behind this section. Teal, green, flare, and navy switch the type to light ink so it stays readable.
   */
  background?: ('paper' | 'tint' | 'teal' | 'field' | 'flare' | 'navy') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'projectLedger';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GrantRequestBlock".
 */
export interface GrantRequestBlock {
  statement?: string | null;
  heading?: string | null;
  intro?: string | null;
  /**
   * Optional photograph under the statement, beside the form. Leave blank to use a recent public photo.
   */
  photo?: (number | null) | Media;
  /**
   * CSS object-position, such as center or 30% 40%, so faces stay in crop.
   */
  photoPosition?: string | null;
  /**
   * Fill behind this section. Teal, green, flare, and navy switch the type to light ink so it stays readable.
   */
  background?: ('paper' | 'tint' | 'teal' | 'field' | 'flare' | 'navy') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'grantRequest';
}
/**
 * Upcoming versus past is determined by end date, or start date when no end date exists. Upcoming sorts soonest first; past sorts newest first.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  /**
   * Start of the event. Used to decide upcoming versus past when there is no end date.
   */
  startDate: string;
  /**
   * Optional. When present, this date decides whether the event is still upcoming.
   */
  endDate?: string | null;
  location?: string | null;
  summary?: string | null;
  image?: (number | null) | Media;
  /**
   * Optional link for tickets, Facebook, or more information. Opens as an external link on the site.
   */
  externalUrl?: string | null;
  /**
   * Cancelled events still appear, clearly marked, instead of disappearing.
   */
  cancelled?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Funded projects and grants. Record year, amount or funding detail, recipient, and who benefited. Do not invent amounts or outcomes.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  /**
   * The year this project was funded or completed.
   */
  year: number;
  /**
   * Stored as playground, facility, equipment, camp, scholarship, or other. The public Projects & Grants page groups these into the five client categories.
   */
  category: 'playground' | 'facility' | 'equipment' | 'camp' | 'scholarship' | 'other';
  /**
   * Public funding detail, such as $5,000 or in-kind equipment. Leave blank if the amount is not confirmed.
   */
  amountLabel?: string | null;
  /**
   * Who received the funds or equipment.
   */
  recipient?: string | null;
  /**
   * Optional link to a supported organization or facility.
   */
  organization?: (number | null) | Organization;
  /**
   * Who benefited, in plain language.
   */
  beneficiaries?: string | null;
  /**
   * Short public description. Be specific and do not invent outcomes.
   */
  summary: string;
  image?: (number | null) | Media;
  /**
   * Show this project in Featured projects sections. Up to four, newest first.
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Current volunteer board members. Leave fields empty rather than inventing titles or bios.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "board-members".
 */
export interface BoardMember {
  id: number;
  name: string;
  /**
   * Board role, such as President or Member. Optional.
   */
  title?: string | null;
  /**
   * Optional headshot. The public site works without a photo.
   */
  photo?: (number | null) | Media;
  /**
   * Short optional biography. Do not invent personal details.
   */
  bio?: string | null;
  /**
   * Optional public link.
   */
  website?: string | null;
  /**
   * Lower numbers appear first.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Questions from the public contact form. Status and internal notes never appear on the website. The public form creates records through a server action; the REST API is staff-only.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  name: string;
  email: string;
  /**
   * Optional. Public visitors may leave this blank.
   */
  phone?: string | null;
  subject: string;
  message: string;
  /**
   * Internal workflow only. Never shown publicly.
   */
  status: 'new' | 'reviewing' | 'follow-up' | 'approved' | 'declined' | 'closed';
  /**
   * Staff notes. Never returned to the public site or confirmation screens.
   */
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Grant requests from the public form. Attachments must be PDF. Status and notes are staff-only. The public form creates records through a server action; the REST API is staff-only.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "grant-requests".
 */
export interface GrantRequest {
  id: number;
  organizationName: string;
  contactName: string;
  email: string;
  phone: string;
  /**
   * Optional public website for the requesting group.
   */
  website?: string | null;
  projectTitle: string;
  beneficiaries?: string | null;
  recreationImpact?: string | null;
  requestedTimeline?: string | null;
  /**
   * What the grant would support, who would benefit, and any confirmed details.
   */
  description: string;
  /**
   * Optional. Use a dollar amount or a short description such as equipment only.
   */
  amountRequested?: string | null;
  /**
   * Optional PDF only. Stored as an internal file and never shown on the public site.
   */
  attachment?: (number | null) | Media;
  /**
   * Internal workflow only. Never shown publicly.
   */
  status: 'new' | 'reviewing' | 'follow-up' | 'approved' | 'declined' | 'closed';
  /**
   * Staff notes. Never returned to the public site or confirmation screens.
   */
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Admin accounts can manage users and site settings. Editors manage public content and submissions.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Admins manage users and settings. Editors manage public content and form submissions.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'organizations';
        value: number | Organization;
      } | null)
    | ({
        relationTo: 'board-members';
        value: number | BoardMember;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null)
    | ({
        relationTo: 'grant-requests';
        value: number | GrantRequest;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        mission?: T | MissionBlockSelect<T>;
        impact?: T | ImpactBlockSelect<T>;
        organizations?: T | OrganizationsBlockSelect<T>;
        featuredProjects?: T | FeaturedProjectsBlockSelect<T>;
        photoRail?: T | PhotoRailBlockSelect<T>;
        upcomingEvents?: T | UpcomingEventsBlockSelect<T>;
        donateCta?: T | DonateCtaBlockSelect<T>;
        contact?: T | ContactBlockSelect<T>;
        masthead?: T | MastheadBlockSelect<T>;
        boardList?: T | BoardListBlockSelect<T>;
        eventList?: T | EventListBlockSelect<T>;
        projectLedger?: T | ProjectLedgerBlockSelect<T>;
        grantRequest?: T | GrantRequestBlockSelect<T>;
      };
  showInNav?: T;
  navLabel?: T;
  navOrder?: T;
  metaTitle?: T;
  metaDescription?: T;
  ogImage?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroBlock_select".
 */
export interface HeroBlockSelect<T extends boolean = true> {
  heading?: T;
  photos?:
    | T
    | {
        image?: T;
        position?: T;
        id?: T;
      };
  fallbackImage?: T;
  fallbackImagePosition?: T;
  secondaryLabel?: T;
  secondaryHref?: T;
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MissionBlock_select".
 */
export interface MissionBlockSelect<T extends boolean = true> {
  heading?: T;
  highlight?: T;
  body?: T;
  note?: T;
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ImpactBlock_select".
 */
export interface ImpactBlockSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  stories?:
    | T
    | {
        heading?: T;
        body?: T;
        proofLabel?: T;
        id?: T;
      };
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OrganizationsBlock_select".
 */
export interface OrganizationsBlockSelect<T extends boolean = true> {
  heading?: T;
  organizations?: T;
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FeaturedProjectsBlock_select".
 */
export interface FeaturedProjectsBlockSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  emptyMessage?: T;
  allLabel?: T;
  allHref?: T;
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PhotoRailBlock_select".
 */
export interface PhotoRailBlockSelect<T extends boolean = true> {
  heading?: T;
  slides?:
    | T
    | {
        image?: T;
        id?: T;
      };
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "UpcomingEventsBlock_select".
 */
export interface UpcomingEventsBlockSelect<T extends boolean = true> {
  heading?: T;
  limit?: T;
  emptyHeading?: T;
  emptyMessage?: T;
  allLabel?: T;
  allHref?: T;
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DonateCtaBlock_select".
 */
export interface DonateCtaBlockSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  secondaryLabel?: T;
  secondaryHref?: T;
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactBlock_select".
 */
export interface ContactBlockSelect<T extends boolean = true> {
  statement?: T;
  heading?: T;
  intro?: T;
  photo?: T;
  photoPosition?: T;
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MastheadBlock_select".
 */
export interface MastheadBlockSelect<T extends boolean = true> {
  heading?: T;
  lede?: T;
  photo?: T;
  photoFallbackIndex?: T;
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BoardListBlock_select".
 */
export interface BoardListBlockSelect<T extends boolean = true> {
  heading?: T;
  emptyHeading?: T;
  emptyMessage?: T;
  emptyNote?: T;
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EventListBlock_select".
 */
export interface EventListBlockSelect<T extends boolean = true> {
  upcomingHeading?: T;
  pastHeading?: T;
  emptyHeading?: T;
  emptyMessage?: T;
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProjectLedgerBlock_select".
 */
export interface ProjectLedgerBlockSelect<T extends boolean = true> {
  categoryHeading?: T;
  categoryIntro?: T;
  heading?: T;
  confirmationNote?: T;
  emptyHeading?: T;
  emptyMessage?: T;
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GrantRequestBlock_select".
 */
export interface GrantRequestBlockSelect<T extends boolean = true> {
  statement?: T;
  heading?: T;
  intro?: T;
  photo?: T;
  photoPosition?: T;
  background?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  startDate?: T;
  endDate?: T;
  location?: T;
  summary?: T;
  image?: T;
  externalUrl?: T;
  cancelled?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  year?: T;
  category?: T;
  amountLabel?: T;
  recipient?: T;
  organization?: T;
  beneficiaries?: T;
  summary?: T;
  image?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations_select".
 */
export interface OrganizationsSelect<T extends boolean = true> {
  name?: T;
  website?: T;
  logo?: T;
  summary?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "board-members_select".
 */
export interface BoardMembersSelect<T extends boolean = true> {
  name?: T;
  title?: T;
  photo?: T;
  bio?: T;
  website?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  decorative?: T;
  visibility?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        feature?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  subject?: T;
  message?: T;
  status?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "grant-requests_select".
 */
export interface GrantRequestsSelect<T extends boolean = true> {
  organizationName?: T;
  contactName?: T;
  email?: T;
  phone?: T;
  website?: T;
  projectTitle?: T;
  beneficiaries?: T;
  recreationImpact?: T;
  requestedTimeline?: T;
  description?: T;
  amountRequested?: T;
  attachment?: T;
  status?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Site-wide name, donation link, and contact details. Admins manage these settings.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  /**
   * Optional short line used near the logo. Keep it concrete.
   */
  tagline?: string | null;
  /**
   * Approved Friends of Recreation logo. Required before final brand colors are sampled.
   */
  logo?: (number | null) | Media;
  /**
   * External donation page. Leave blank until the board confirms the URL. The site will not invent a payment link.
   */
  donationUrl?: string | null;
  /**
   * Label for the public Donate control.
   */
  donationLabel?: string | null;
  /**
   * Optional Facebook page URL.
   */
  facebookUrl?: string | null;
  /**
   * Optional public contact address shown in the footer.
   */
  contactEmail?: string | null;
  /**
   * Where contact and grant form notifications are sent. Never shown on the public site.
   */
  notificationEmail?: string | null;
  /**
   * Optional footer line, such as volunteer-led in Saratoga Springs, New York.
   */
  footerNote?: string | null;
  /**
   * Fallback search description for pages that do not set their own. Homepage copy is stored on the Home page.
   */
  defaultDescription?: string | null;
  /**
   * Default Open Graph image for social shares. Use a wide recreation photograph, about 1200×630. Falls back to the logo if empty.
   */
  defaultSocialImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  logo?: T;
  donationUrl?: T;
  donationLabel?: T;
  facebookUrl?: T;
  contactEmail?: T;
  notificationEmail?: T;
  footerNote?: T;
  defaultDescription?: T;
  defaultSocialImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}