/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'board-members': BoardMember;
    events: Event;
    projects: Project;
    organizations: Organization;
    'contact-submissions': ContactSubmission;
    'grant-requests': GrantRequest;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'board-members': BoardMembersSelect<false> | BoardMembersSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    organizations: OrganizationsSelect<false> | OrganizationsSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'grant-requests': GrantRequestsSelect<false> | GrantRequestsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'home-page': HomePage;
    'page-content': PageContent;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'page-content': PageContentSelect<false> | PageContentSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Admin accounts can manage users and site settings. Editors manage public content and submissions.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Admins manage users and settings. Editors manage public content and form submissions.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Photographs and files for the public site. Grant PDFs are stored as internal files and are never shown publicly. Production should use object storage via S3 environment variables.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the image for screen readers. Required for every file, including decorative photos.
   */
  alt: string;
  /**
   * Internal files, including grant PDFs, are never returned to the public website.
   */
  visibility: 'public' | 'internal';
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    feature?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Current volunteer board members. Leave fields empty rather than inventing titles or bios.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "board-members".
 */
export interface BoardMember {
  id: number;
  name: string;
  /**
   * Board role, such as President or Member. Optional.
   */
  title?: string | null;
  /**
   * Optional headshot. The public site works without a photo.
   */
  photo?: (number | null) | Media;
  /**
   * Short optional biography. Do not invent personal details.
   */
  bio?: string | null;
  /**
   * Optional public link.
   */
  website?: string | null;
  /**
   * Lower numbers appear first.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Upcoming versus past is determined by end date, or start date when no end date exists. Upcoming sorts soonest first; past sorts newest first.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  /**
   * Start of the event. Used to decide upcoming versus past when there is no end date.
   */
  startDate: string;
  /**
   * Optional. When present, this date decides whether the event is still upcoming.
   */
  endDate?: string | null;
  location?: string | null;
  summary?: string | null;
  image?: (number | null) | Media;
  /**
   * Optional link for tickets, Facebook, or more information. Opens as an external link on the site.
   */
  externalUrl?: string | null;
  /**
   * Cancelled events still appear, clearly marked, instead of disappearing.
   */
  cancelled?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Funded projects and grants. Record year, amount or funding detail, recipient, and who benefited. Do not invent amounts or outcomes.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  /**
   * The year this project was funded or completed.
   */
  year: number;
  /**
   * Used to group projects without forcing every story into the same card layout.
   */
  category: 'playground' | 'facility' | 'equipment' | 'camp' | 'scholarship' | 'other';
  /**
   * Public funding detail, such as $5,000 or in-kind equipment. Leave blank if the amount is not confirmed.
   */
  amountLabel?: string | null;
  /**
   * Who received the funds or equipment.
   */
  recipient?: string | null;
  /**
   * Optional link to a supported organization or facility.
   */
  organization?: (number | null) | Organization;
  /**
   * Who benefited, in plain language.
   */
  beneficiaries?: string | null;
  /**
   * Short public description. Be specific and do not invent outcomes.
   */
  summary: string;
  image?: (number | null) | Media;
  /**
   * Show this project on the homepage featured strip. Up to four, newest first.
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Recreation programs, facilities, and partners that Friends of Recreation supports. Do not invent partners.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations".
 */
export interface Organization {
  id: number;
  name: string;
  /**
   * Optional public website.
   */
  website?: string | null;
  /**
   * Optional logo. Keep organization logos secondary to photography on the public site.
   */
  logo?: (number | null) | Media;
  /**
   * One or two sentences about this program or facility.
   */
  summary?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Questions from the public contact form. Status and internal notes never appear on the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  name: string;
  email: string;
  /**
   * Optional. Public visitors may leave this blank.
   */
  phone?: string | null;
  subject: string;
  message: string;
  /**
   * Internal workflow only. Never shown publicly.
   */
  status: 'new' | 'in-progress' | 'closed';
  /**
   * Staff notes. Never returned to the public site or confirmation screens.
   */
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Grant requests from the public form. Attachments must be PDF. Status and notes are staff-only.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "grant-requests".
 */
export interface GrantRequest {
  id: number;
  organizationName: string;
  contactName: string;
  email: string;
  phone?: string | null;
  /**
   * Optional public website for the requesting group.
   */
  website?: string | null;
  projectTitle: string;
  beneficiaries?: string | null;
  recreationImpact?: string | null;
  requestedTimeline?: string | null;
  /**
   * What the grant would support, who would benefit, and any confirmed details.
   */
  description: string;
  /**
   * Optional. Use a dollar amount or a short description such as equipment only.
   */
  amountRequested?: string | null;
  /**
   * Optional PDF only. Stored as an internal file and never shown on the public site.
   */
  attachment?: (number | null) | Media;
  /**
   * Internal workflow only. Never shown publicly.
   */
  status: 'new' | 'in-review' | 'awarded' | 'declined' | 'closed';
  /**
   * Staff notes. Never returned to the public site or confirmation screens.
   */
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'board-members';
        value: number | BoardMember;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'organizations';
        value: number | Organization;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null)
    | ({
        relationTo: 'grant-requests';
        value: number | GrantRequest;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  visibility?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        feature?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "board-members_select".
 */
export interface BoardMembersSelect<T extends boolean = true> {
  name?: T;
  title?: T;
  photo?: T;
  bio?: T;
  website?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  startDate?: T;
  endDate?: T;
  location?: T;
  summary?: T;
  image?: T;
  externalUrl?: T;
  cancelled?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  year?: T;
  category?: T;
  amountLabel?: T;
  recipient?: T;
  organization?: T;
  beneficiaries?: T;
  summary?: T;
  image?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations_select".
 */
export interface OrganizationsSelect<T extends boolean = true> {
  name?: T;
  website?: T;
  logo?: T;
  summary?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  subject?: T;
  message?: T;
  status?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "grant-requests_select".
 */
export interface GrantRequestsSelect<T extends boolean = true> {
  organizationName?: T;
  contactName?: T;
  email?: T;
  phone?: T;
  website?: T;
  projectTitle?: T;
  beneficiaries?: T;
  recreationImpact?: T;
  requestedTimeline?: T;
  description?: T;
  amountRequested?: T;
  attachment?: T;
  status?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Site-wide name, donation link, and contact details. Admins manage these settings.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  /**
   * Optional short line used near the logo. Keep it concrete.
   */
  tagline?: string | null;
  /**
   * Approved Friends of Recreation logo. Required before final brand colors are sampled.
   */
  logo?: (number | null) | Media;
  /**
   * External donation page. Leave blank until the board confirms the URL. The site will not invent a payment link.
   */
  donationUrl?: string | null;
  /**
   * Label for the public Donate control.
   */
  donationLabel?: string | null;
  /**
   * Optional Facebook page URL.
   */
  facebookUrl?: string | null;
  /**
   * Optional public contact address shown in the footer.
   */
  contactEmail?: string | null;
  /**
   * Where contact and grant form notifications are sent. Never shown on the public site.
   */
  notificationEmail?: string | null;
  /**
   * Optional footer line, such as volunteer-led in Saratoga Springs, New York.
   */
  footerNote?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Homepage mission, impact, featured projects, donation copy, and contact intro. Editors can update this content.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  /**
   * Starter wording until the board approves final language. Keep it short enough to stay on the first screen with Donate.
   */
  missionHeading: string;
  /**
   * One or two sentences explaining the mission in plain language.
   */
  missionBody: string;
  /**
   * Add 1 photograph, or 3 for an offset cluster. Two also works. These plates sit beside the headline — they are not the photo slider.
   */
  heroPhotos?:
    | {
        image: number | Media;
        /**
         * CSS object-position, such as center or 30% 40%, so faces stay in crop.
         */
        position?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Fallback if Hero photographs is empty. Prefer the photographs list above.
   */
  heroImage?: (number | null) | Media;
  /**
   * Used only with the fallback hero image.
   */
  heroImagePosition?: string | null;
  impactHeading?: string | null;
  /**
   * Optional. Keep this to how Friends of Recreation helps, not invented outcomes.
   */
  impactIntro?: string | null;
  /**
   * Up to three impact stories. They are typeset as a manifesto — a loud heading, named-place proof, and a reading column — not as matching cards. Leave empty rather than inventing results.
   */
  impactStories?:
    | {
        heading: string;
        body: string;
        /**
         * Optional inscribed proof, such as a year, amount, or recipient. Leave blank if unconfirmed.
         */
        proofLabel?: string | null;
        id?: string | null;
      }[]
    | null;
  organizationsHeading?: string | null;
  /**
   * Supported programs and facilities to highlight on the homepage.
   */
  featuredOrganizations?: (number | Organization)[] | null;
  photoSliderHeading?: string | null;
  /**
   * Homepage photo slider. Add recreation photographs only. Organization logos belong on each Organization record, not here.
   */
  photoSlider?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  projectsHeading?: string | null;
  /**
   * The homepage now reads the Featured checkbox on each project (newest first, up to four). This relationship is not used for the public homepage.
   */
  featuredProjects?: (number | Project)[] | null;
  donationHeading?: string | null;
  /**
   * Short donation reprise. Do not invent a payment processor or URL.
   */
  donationBody?: string | null;
  contactHeading?: string | null;
  /**
   * Short intro above the homepage contact form.
   */
  contactIntro?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Intro copy and empty states for Board Members, Events, and Projects & Grants.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-content".
 */
export interface PageContent {
  id: number;
  board?: {
    heading?: string | null;
    /**
     * Optional introduction. Do not invent board biographies here.
     */
    intro?: string | null;
    emptyMessage?: string | null;
  };
  events: {
    heading?: string | null;
    intro?: string | null;
    /**
     * Shown when there are no upcoming published events. May point people to Facebook.
     */
    emptyUpcomingMessage: string;
  };
  projects?: {
    heading?: string | null;
    intro?: string | null;
    grantHeading?: string | null;
    /**
     * Explains the grant request form. Do not promise an application portal.
     */
    grantIntro?: string | null;
    emptyMessage?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  logo?: T;
  donationUrl?: T;
  donationLabel?: T;
  facebookUrl?: T;
  contactEmail?: T;
  notificationEmail?: T;
  footerNote?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  missionHeading?: T;
  missionBody?: T;
  heroPhotos?:
    | T
    | {
        image?: T;
        position?: T;
        id?: T;
      };
  heroImage?: T;
  heroImagePosition?: T;
  impactHeading?: T;
  impactIntro?: T;
  impactStories?:
    | T
    | {
        heading?: T;
        body?: T;
        proofLabel?: T;
        id?: T;
      };
  organizationsHeading?: T;
  featuredOrganizations?: T;
  photoSliderHeading?: T;
  photoSlider?:
    | T
    | {
        image?: T;
        id?: T;
      };
  projectsHeading?: T;
  featuredProjects?: T;
  donationHeading?: T;
  donationBody?: T;
  contactHeading?: T;
  contactIntro?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-content_select".
 */
export interface PageContentSelect<T extends boolean = true> {
  board?:
    | T
    | {
        heading?: T;
        intro?: T;
        emptyMessage?: T;
      };
  events?:
    | T
    | {
        heading?: T;
        intro?: T;
        emptyUpcomingMessage?: T;
      };
  projects?:
    | T
    | {
        heading?: T;
        intro?: T;
        grantHeading?: T;
        grantIntro?: T;
        emptyMessage?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}